config/routes.rb
RailsBootstrap::Application.routes.draw do
  get 'workers' => 'workers#index', as: :workers

  get 'ucls' => 'ucls#index', as: :ucls
  root :to => 'visitors#new'

  resources :instruments, only: [:new, :create, :show, :edit, :destroy, :update]
  resources :observation_sections, only: [:edit, :update]
  resources :evaluation_events, only: [:new, :create]
end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  belongs_to :ucl
  has_many :evaluation_events, inverse_of: :instrument

  has_many :observation_sections, inverse_of: :instrument, dependent: :destroy
  has_many :interview_sections, inverse_of: :instrument, dependent: :destroy

  ## VALIDATIONS
  validates :name, presence: true
  validates :ucl, presence: true  # all instruments must be related to a valid and real UCL

  ## Explicitly allow setting of observation_section attributes (i.e. observation_questions and interview_questions) through nesting on this model
  accepts_nested_attributes_for :observation_sections, reject_if: lambda {|os| os[:name].blank?}, allow_destroy: true
  accepts_nested_attributes_for :interview_sections, reject_if: lambda {|is| is[:name].blank?}, allow_destroy: true

  # TODO adding proper numbering support in a helper method makes more sense

  ## Allow controller to pass switches to add extra sections
  def _add_observation_section=(switch)
    self.add_blank_observation_section if switch == "1"
  end
  def _add_observation_section
    # default is to NOT add a section
    "0"
  end

  def _add_interview_section=(switch)
    self.add_blank_interview_section if switch == "1"
  end
  def _add_interview_section
    # default is to NOT add a section
    "0"
  end

  def add_blank_observation_section
    observation_sections.create(name: "...")
  end
  def add_blank_interview_section
    interview_sections.create(name: "...")
  end

  def self.options_for_select
    Instrument.all.map{|s| [s.name]}
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  attr_accessor :no_js
  before_action :set_instrument, only: [:edit, :show, :destroy, :update]
  before_action :set_sections, only: [:show, :edit, :new]
  before_action :set_no_js, only: [:edit, :new] # TODO implement JS version so we can turn this off by default

  # GET /instruments/1
  def show
  end

  # GET /instruments/1/edit
  # todo if client has Javascript (option set client-side), render x, else render y (non-javascript form available)
  # default rendering is JS enabled
  def edit
    respond_to do |format|
      format.html
    end
  end

  # PATCH/PUT /instruments/1
  def update
    if @instrument.update(instrument_params)
      redirect_to instrument_url(@instrument), notice: 'Instrument was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /instruments/1
  def destroy
    @instrument.destroy
    flash[:notice] = "Instrument: #{@instrument.name} deleted"
    redirect_to ucls_url
  end

  # GET /instruments/new
  def new
    @instrument = Instrument.new
    @instrument.observation_sections.build # start with empty section field
  end

  # POST /instruments
  def create
    @instrument = Instrument.new(instrument_params)
    respond_to do |format|
      if @instrument.save
        format.html { redirect_to instrument_url(@instrument), notice: "Instrument created successfully!" }
      else
        format.html { render action: :new }
      end
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def instrument_params
    params.require(:instrument).permit(:name, :ucl_id, :_add_observation_section, :_add_interview_section,
                                       observation_sections_attributes: [:id, :name, :_add_question, :_destroy,
                                                                         observation_questions_attributes: [:id, :content, :_destroy]],
                                       interview_sections_attributes: [:id, :name, :_add_question, :_destroy,
                                                                       interview_questions_attributes: [:question_content, :sample_answer, :id, :_destroy]])
  end

  def set_instrument
    @instrument = Instrument.find(params[:id])
  end

  def set_sections
    @observation_sections = ObservationSection.where(:instrument_id => params[:id]).order(id: :asc)
    @interview_sections = InterviewSection.where(:instrument_id => params[:id]).order(id: :asc)
  end

  def set_no_js
    @no_js = true
  end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/instruments/_form.html.haml
= bootstrap_nested_form_for @instrument do |f|
  .form-section
    = f.select :ucl_id, options_for_select(Ucl.options_for_select), label: 'Select UCL for this instrument:'
    = f.text_field :name, label: 'Instrument name:'
    = f.fields_for :observation_sections do |section_f|
      = section_f.text_area :name, label: "Section #X"

app/views/instruments/_form_nojs.html.haml
-# This form works with JS disabled in the browser
= bootstrap_form_for @instrument do |f|
  .form-section
    = f.select :ucl_id, options_for_select(Ucl.options_for_select), label: 'Select UCL for this instrument:'
    = f.text_field :name, label: 'Instrument name:'
  %h3 Observation
  .form-section
    = f.fields_for :observation_sections, @observation_sections do |section_f|
      = render 'observation_section_fields', f: section_f
    = f.check_box :_add_observation_section, label: 'Add Observation Section'
  %h3 Interview
  .form-section
    = f.fields_for :interview_sections, @interview_sections do |section_f|
      = render 'interview_section_fields', f: section_f
    = f.check_box :_add_interview_section, label: 'Add interview Section'
  = f.submit

app/views/instruments/_interview_questions_view.html.haml
%ol
  - interview_section.interview_questions.each do |interview_question|
    %li= interview_question.question_content
    %ul
      %li= content_tag(:i, "#{interview_question.sample_answer}")

app/views/instruments/_interview_section_fields.html.haml
.form-section
  = f.text_area :name, label: 'Section Name' # TODO change to show section number
  = f.check_box :_destroy, label: 'Remove Section'
  = f.fields_for :interview_questions do |question_f|
    = render 'interview_question_fields', f: question_f
    = f.check_box :_add_question, label: 'Add Question'

app/views/instruments/_observation_questions_view.html.haml
%ol
  - observation_section.observation_questions.each do |observation_question|
    %li= observation_question.content

app/views/instruments/_observation_section_fields.html.haml
.form-section
  = f.text_area :name, label: 'Section Name' # TODO change to show section number
  = f.check_box :_destroy, label: 'Remove Section'
  = f.fields_for :observation_questions do |question_f|
    = render 'observation_question_fields', f: question_f
  = f.check_box :_add_question, label: 'Add Question'

app/views/instruments/edit.html.haml
%h3 Edit Instrument

%section
.form
  - if @no_js
    = render 'instruments/nojs/form'
  - else
    = render 'form'

app/views/instruments/new.html.haml
%h3 Create a new Instrument

%section
.form
  - if @no_js
    = render 'instruments/nojs/form'
  - else
    = render 'form'

app/views/instruments/show.html.haml
%h3 Showing Instrument

%section
  .column
    %strong Instrument name:
    %ul
      %li= @instrument.name
    %strong UCL:
    %ul
      %li= @instrument.ucl.human_readable_name
    - if @instrument.observation_sections.count == 0 # todo move to model
      %strong No Observation Sections
    - else
      %strong Observation Sections
      %ol{type: "A"}
        - @observation_sections.each do |observation_section|
          %li= observation_section.name
          = render partial: 'observation_questions_view', locals: {observation_section: observation_section}
      %strong Interview Sections
      %ol{type: "A"}
        - @interview_sections.each do |interview_section|
          %li= interview_section.name
          = render partial: 'interview_questions_view', locals: {interview_section: interview_section}
%section
  .column
    = button_to 'Edit Instrument', edit_instrument_path(@instrument), class: 'button', method: :get
    = button_to 'Delete Instrument', instrument_path(@instrument), class: 'button', method: :delete, data: {confirm: 'Really delete this instrument?'}