config/routes.rb
RailsBootstrap::Application.routes.draw do
  get 'workers' => 'workers#index', as: :workers

  get 'ucls' => 'ucls#index', as: :ucls
  root :to => 'visitors#new'

  resources :instruments, only: [:new, :create, :show, :edit, :destroy, :update]
  resources :observation_sections, only: [:edit, :update]
  resources :evaluation_events, only: [:new, :create]
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
-# add navigation links to this file
%li= link_to 'Start Evaluation', new_evaluation_event_path
%li= link_to 'Create Instrument', new_instrument_path
%li= link_to 'UCLs', ucls_path
%li= link_to 'Workers', workers_path
%li= link_to 'About', page_path('about')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'InnovaCert'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Rails Bootstrap'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main", :class => "container"}
      .row
        .col-lg-12
          = render 'layouts/messages'
          = yield
    %footer.container
      .row
        %section.col-sm-4.col-sm-offset-4.text-center
          Copyright SlyWorks 2014, all rights reserved.